name: Desplegar Microservicio

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configurar Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configurar Docker para usar gcloud como helper
      run: |
        gcloud auth configure-docker

    - name: Instalar Buildx
      run: |
        docker run --privileged --rm tonistiigi/binfmt --install all
        docker buildx create --use

    - name: Construir la imagen Docker usando Buildx
      run: |
        docker buildx build --platform linux/amd64 -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/pruebatecnica:$GITHUB_SHA --push .

    - name: Actualizar despliegue en Kubernetes
      run: |
        kubectl set image deployment/pruebatecnica pruebatecnica=gcr.io/${{ secrets.GCP_PROJECT_ID }}/pruebatecnica:$GITHUB_SHA
