name: Desplegar Microservicio

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configurar Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configurar Docker
      run: |
        gcloud auth configure-docker

    - name: Construir la imagen Docker
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/pruebatecnica:$GITHUB_SHA .

    - name: Push de la imagen a GCR
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/pruebatecnica:$GITHUB_SHA

    - name: Actualizar despliegue en Kubernetes
      run: |
        kubectl set image deployment/pruebatecnica pruebatecnica=gcr.io/${{ secrets.GCP_PROJECT_ID }}/pruebatecnica:$GITHUB_SHA
